name: AWS CDK Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/lambda_test/requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install CDK dependencies
        run: npm install -g aws-cdk
      - name: Install project dependencies
        run: npm install --include=dev
      - name: Build CDK
        run: npm run build
      - name: Run CDK tests
        run: npm run test